import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const features = [
  { icon: '🤖', title: 'AI-Generated Questions', desc: 'Dynamic questions tailored to your chosen topic and difficulty level.' },
  { icon: '📊', title: 'Instant Feedback', desc: 'Get scored on accuracy, communication, and problem-solving after every answer.' },
  { icon: '📈', title: 'Track Progress', desc: 'Visual analytics to see your growth over time across all topics.' },
  { icon: '🎯', title: 'Multiple Domains', desc: 'DSA, Web Dev, Machine Learning, and CS Fundamentals covered.' },
];

const topics = [
  { label: 'Data Structures & Algorithms', color: 'bg-indigo-100 text-indigo-700', tag: 'DSA' },
  { label: 'Web Development',              color: 'bg-blue-100 text-blue-700',    tag: 'WEB' },
  { label: 'Machine Learning',             color: 'bg-purple-100 text-purple-700',tag: 'ML'  },
  { label: 'CS Fundamentals',              color: 'bg-green-100 text-green-700',  tag: 'CS'  },
];

export default function Landing() {
  const { user } = useAuth();

  return (
    <div className="min-h-screen bg-white">
      {/* Navbar */}
      <nav className="flex items-center justify-between px-8 py-4 border-b">
        <span className="text-xl font-bold text-indigo-600">InterviewForge</span>
        <div className="flex gap-3">
          {user ? (
            <Link to="/dashboard" className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700">
              Go to Dashboard
            </Link>
          ) : (
            <>
              <Link to="/login"    className="text-gray-600 px-4 py-2 rounded-lg text-sm hover:bg-gray-100">Login</Link>
              <Link to="/register" className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700">Get Started</Link>
            </>
          )}
        </div>
      </nav>

      {/* Hero */}
      <section className="text-center py-24 px-6 bg-gradient-to-b from-indigo-50 to-white">
        <span className="inline-block bg-indigo-100 text-indigo-700 text-xs font-medium px-3 py-1 rounded-full mb-4">
          AI-Powered Mock Interviews
        </span>
        <h1 className="text-5xl font-bold text-gray-900 mb-5 leading-tight">
          Sharpen your skills.<br/>Ace every round.
        </h1>
        <p className="text-gray-500 text-lg max-w-xl mx-auto mb-8">
          Practice real interview questions generated by AI, get instant feedback,
          and track your improvement — all in one place.
        </p>
        <div className="flex gap-3 justify-center">
          <Link to="/register" className="bg-indigo-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-indigo-700">
            Start Practicing Free
          </Link>
          <Link to="/login" className="border border-gray-200 text-gray-700 px-6 py-3 rounded-lg font-medium hover:bg-gray-50">
            Sign In
          </Link>
        </div>
      </section>

      {/* Topics */}
      <section className="py-16 px-8 max-w-5xl mx-auto">
        <h2 className="text-2xl font-bold text-center text-gray-800 mb-8">Topics covered</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {topics.map(t => (
            <div key={t.tag} className={`rounded-xl p-5 text-center ${t.color}`}>
              <p className="text-xs font-bold mb-1">{t.tag}</p>
              <p className="text-sm font-medium">{t.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="py-16 px-8 max-w-5xl mx-auto">
        <h2 className="text-2xl font-bold text-center text-gray-800 mb-10">Everything you need to prepare</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {features.map(f => (
            <div key={f.title} className="border rounded-xl p-6 hover:shadow-sm transition-shadow">
              <div className="text-3xl mb-3">{f.icon}</div>
              <h3 className="font-semibold text-gray-800 mb-1">{f.title}</h3>
              <p className="text-sm text-gray-500">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="bg-indigo-600 text-white text-center py-16 px-6">
        <h2 className="text-3xl font-bold mb-3">Ready to crack your next interview?</h2>
        <p className="text-indigo-200 mb-6">Join thousands of students preparing smarter with AI.</p>
        <Link to="/register" className="bg-white text-indigo-600 font-semibold px-6 py-3 rounded-lg hover:bg-indigo-50">
          Get started — it's free
        </Link>
      </section>

      {/* Footer */}
      <footer className="text-center py-6 text-sm text-gray-400 border-t">
        © 2025 InterviewForge. Built with ❤️ for students.
      </footer>
    </div>
  );
}